SRC_DIR = src
BUILD_DIR_DEBUG = build/debug
BUILD_DIR_RELEASE = build/release
CC = g++
SRC_FILES = $(shell find $(SRC_DIR) -name '*.cpp' -type f)
OBJ_NAME = play
INCLUDE_PATHS = -Iinclude
LIBRARY_PATHS = -Llib
COMPILER_FLAGS_DEBUG = -std=c++20 -Wall -O0 -g
COMPILER_FLAGS_RELEASE = -std=c++20 -Wall -O3
LINKER_FLAGS = -lsdl2

all:
	mkdir -p $(BUILD_DIR_DEBUG)
	$(CC) $(COMPILER_FLAGS_DEBUG) $(LINKER_FLAGS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(SRC_FILES) -o $(BUILD_DIR_DEBUG)/$(OBJ_NAME)

release:
	mkdir -p $(BUILD_DIR_RELEASE)
	$(CC) $(COMPILER_FLAGS_RELEASE) $(LINKER_FLAGS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(SRC_FILES) -o $(BUILD_DIR_RELEASE)/$(OBJ_NAME)
	strip $(BUILD_DIR_RELEASE)/$(OBJ_NAME)